#!/usr/bin/env bash
# create a GPU instance on google cloud
# docs: https://cloud.google.com/compute/docs/gpus/add-gpus#create-new-gpu-instance
# startup script: https://cloud.google.com/compute/docs/startupscript#rerunthescript
# --preemptible \

gcloud compute instances create gpu-instance-3 \
    --machine-type n1-standard-2 \
    --zone us-east1-c \
    --accelerator type=nvidia-tesla-k80 \
    --image-family ubuntu-1604-lts --image-project ubuntu-os-cloud \
    --maintenance-policy TERMINATE --restart-on-failure \
    --boot-disk-size 100GB \
    --metadata startup-script='#!/bin/bash
    echo "Checking for CUDA and installing."
    # Check for CUDA and try to install.
    if ! dpkg-query -W cuda-8-0; then
      curl -O https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
      dpkg -i ./cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
      apt-get update
      apt-get install cuda-8-0 -y
    fi'
