data:
  root_folder: /Users/Edu/data/yass
  recordings: 7ch.bin
  geometry: geometry.txt

resources:
  max_memory: 100MB

recordings:
  dtype: int16
  sampling_rate: 20000
  n_channels: 7
  spatial_radius: 70
  spike_size_ms: 1.5
  order: samples

preprocess:
  apply_filter: True
  dtype: float32

detect:
  method: threshold
  temporal_features: 3
