data:
  root_folder: /home/Edu/data/retinal
  recordings: ej49_data1_set1.bin
  geometry: ej49_geometry1.txt

resources:
  max_memory: 50MB
  max_memory_gpu: 10MB

recordings:
  dtype: int16
  sampling_rate: 20000
  n_channels: 49
  spatial_radius: 70
  spike_size_ms: 1.5
  order: samples
