data:
  root_folder: /home/Edu/data/sample-data/
  recordings: retinal.bin
  geometry: retinal_geom.txt

resources:
  max_memory: 50MB
  max_memory_gpu: 10MB

recordings:
  dtype: int16
  sampling_rate: 20000
  n_channels: 49
  spatial_radius: 70
  spike_size_ms: 2
  order: samples

preprocess:
  apply_filter: True
  dtype: float32

detect:
  method: nn
  temporal_features: 3
