data:
  root_folder: /ssd/data/eduardo
  recordings: fullej.dat 
  geometry: 512coords.txt

resources:
  max_memory: 1700KB
  multi_processing: True
  n_processors: 12 
  n_sec_chunk: 1

recordings:
  dtype: int16
  sampling_rate: 20000
  n_channels: 49
  spatial_radius: 70
  spike_size_ms: 1
  order: samples

preprocess:
  apply_filter: True
  dtype: float32

detect:
  method: threshold
  temporal_features: 3
