data:
  root_folder: /home/Edu/data
  recordings: retinal_10min.bin
  geometry: 512coords.txt

resources:
  max_memory: 500MB 

recordings:
  dtype: int16
  sampling_rate: 20000
  n_channels: 512
  spatial_radius: 70
  spike_size_ms: 1
  order: samples

preprocess:
  apply_filter: True
  dtype: float32

detect:
  method: threshold
  temporal_features: 3
