#!/usr/bin/env bash
# Install software in GPU instance
# GPU instances docs https://cloud.google.com/compute/docs/gpus/add-gpus#create-new-gpu-instance

# gcloud compute scp ./libcudnn7_7.1.4.18-1+cuda9.0_amd64.deb \
#     yass-machine:~ --zone us-east1-c

# libcudnn
sudo dpkg -i libcudnn7_7.1.4.18-1+cuda9.0_amd64.deb
rm -f libcudnn7_7.1.4.18-1+cuda9.0_amd64.deb
 
cd $HOME

# essentials
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install bzip2 git htop

# miniconda
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
source ~/.bashrc

# dotfiles
mkdir dev && cd dev
git clone https://github.com/edublancas/dotfiles
python dotfiles/setup/make_symlinks
source ~/.bashrc

# yass
git clone https://github.com/paninski-lab/yass
cd yass
pip install -r requirements.txt

pip install --upgrade pip
pip install -e .

# tensorflow
pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.8.0-cp36-cp36m-linux_x86_64.whl
